# Generated by Django 3.2.7 on 2021-09-21 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatormodel',
            name='plan',
            field=models.CharField(max_length=255, null=True, verbose_name='значение план'),
        ),
        migrations.AlterField(
            model_name='indicatormodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
