# Generated by Django 3.2.7 on 2021-09-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210921_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatormodel',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='indicatormodel',
            name='plan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='значение план'),
        ),
    ]
