# Generated by Django 3.2.7 on 2021-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210927_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatormodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='показатель'),
        ),
    ]
