# Generated by Django 3.2.7 on 2021-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kp1', models.PositiveIntegerField()),
                ('kp2', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
