# Generated by Django 3.2.7 on 2021-09-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='kp1',
            new_name='fact',
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='kp2',
            new_name='plan',
        ),
    ]
